title: summary
email: 64@live.jp
description: portfolio.
baseurl: ""
url: "https://kat-atat.github.io"
github_username:  kat-atat

author: "*nikki"

defaults:
  - values:
      layout: "default"

# Build settings
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
